apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: zero-to-prod-app-alerts
  labels:
    release: kube-prometheus-stack
spec:
  groups:
    - name: zero-to-prod-app
      rules:
        - alert: AppDown
          expr: up{job="zero-to-prod-app"} == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "zero-to-prod-app is down"
            description: "{{ $labels.instance }} has been down for more than 1 minute."
