apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: zero-to-prod-app
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: zero-to-prod-app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
